name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci
      
      # Guard against SW registration regressions
      - name: Verify No SW Registration
        run: node scripts/verify-no-sw-register.mjs
      
      - run: npm run build
      
      # Run comprehensive QA checks
      - name: Run QA Verification
        run: node scripts/comprehensive-qa.mjs
      
      # Run performance audit
      - name: Run Performance Audit
        run: node scripts/performance-audit.mjs

      # Upload only ./dist (einzige Quelle der Wahrheit)
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4